/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.confrence;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Jackman
 */
public class EventUI extends javax.swing.JFrame {

    /**
     * Creates new form Event
     */
    public EventUI() {
        initComponents();
    }
    DateFormat df = new SimpleDateFormat("MM-dd-yyyy");
    
    
    private String customerID; 
    private String room;
    private int guestNum;
    private Double totalPrice = 0.00;
    private String eventID;
    Connection conn = null;
    ArrayList<Item> itemList = new ArrayList<Item>();
    int internal;
   
    //Stores a unique ID for each new object
    String ID ;
    //Stores a new number for each new object
    static int uniqueNum;
    
    public double getTotalPrice()
    {
        return totalPrice;
    }
    
    private void setTotalPrice(double num)
    {
        totalPrice = totalPrice +num;
        totalTxt.setText( totalPrice.toString());
    }
    
    public int getUniqueNum()
    {
         try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/eventdatabase","root","");
            System.out.println("Connection Successful");
            Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT * FROM idCounter");
            
            while (rs.next())
                {
            uniqueNum = rs.getInt("Count");
            
                }
            
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception1! ");
            System.err.println(e.getMessage());
        }
         return uniqueNum;
    }
    
    //Returns an ID
    public String getID() {
        return ID;
    }
    
    //increments the uniqueNum by 1 and saves the new ID
    private String setID(){
        uniqueNum = getUniqueNum() +1;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/eventdatabase","root","");
            System.out.println("Connection Successful");
            Statement stmt = conn.createStatement();
            stmt.executeUpdate("UPDATE idcounter SET count = '"+uniqueNum+"' WHERE ref = 'ref'");
        }
        catch (Exception e)
    {
      System.err.println("D'oh! Got an exception2!"); 
      e.printStackTrace();
      System.err.println(e.getMessage()); 
    
    } 
       return ID = "UC" + uniqueNum; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        streetNameTxt = new javax.swing.JTextField();
        houseNumberTxt = new javax.swing.JTextField();
        postCodeTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        interRBtn = new javax.swing.JRadioButton();
        exterRBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        startTxt = new javax.swing.JTextField();
        endTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        startDateTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        createEventBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        menuCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        drinksCombo = new javax.swing.JComboBox<>();
        quantityMenuCombo = new javax.swing.JComboBox<>();
        quantityDrinksCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectedMenus = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedDrinks = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        endDateTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        numOfGuests = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        roomComboBox = new javax.swing.JComboBox<>();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Details");

        jLabel2.setText("Full Name");

        customerNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setText("Street Name");

        jLabel5.setText("House Number");

        jLabel6.setText("Post Code");

        postCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postCodeTxtActionPerformed(evt);
            }
        });

        interRBtn.setText("Internal");
        interRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interRBtnActionPerformed(evt);
            }
        });

        exterRBtn.setText("External");
        exterRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exterRBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Event Details");

        jLabel9.setText("Start Date");

        jLabel10.setText("Start Time");

        jLabel11.setText("End Time");

        startTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTxtActionPerformed(evt);
            }
        });

        jLabel12.setText("Room");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Catering");

        createEventBtn.setText("Create New Event");
        createEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Menu");

        menuCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu 1", "Menu 2", "Menu 3", "Menu 4" }));
        menuCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComboActionPerformed(evt);
            }
        });

        jLabel15.setText("Drinks");

        drinksCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Champagne", "Red Wine", "White Wine", "Beer", "Apple Juice", "Orange Juice" }));
        drinksCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksComboActionPerformed(evt);
            }
        });

        quantityMenuCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        quantityDrinksCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        selectedMenus.setEditable(false);
        selectedMenus.setColumns(20);
        selectedMenus.setRows(5);
        jScrollPane1.setViewportView(selectedMenus);

        selectedDrinks.setEditable(false);
        selectedDrinks.setColumns(20);
        selectedDrinks.setRows(5);
        jScrollPane2.setViewportView(selectedDrinks);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Email");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Telephone");

        jLabel18.setText("End Date");

        jLabel19.setText("Number of guests");

        numOfGuests.setName("numOfGuests"); // NOI18N

        totalTxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Total");

        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField3.setText("£");

        jButton1.setText("Save Changes");

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meade ", "Meade Suite", "Hicks ", "Cormack ", "Boardroom A", "Boardroom B", "Barker " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(streetNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interRBtn)
                                .addGap(42, 42, 42)
                                .addComponent(exterRBtn))
                            .addComponent(customerNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(houseNumberTxt)
                            .addComponent(postCodeTxt)
                            .addComponent(emailTxt)
                            .addComponent(telTxt)))
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantityMenuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantityDrinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(drinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(endTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(startTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(startDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(endDateTxt)
                                    .addComponent(numOfGuests)
                                    .addComponent(roomComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(createEventBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(startDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exterRBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(endDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(startTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(endTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(numOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addComponent(jLabel13)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(quantityMenuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(menuCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addComponent(totalTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(interRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(houseNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(postCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearBtn)
                            .addComponent(createEventBtn)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityDrinksCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postCodeTxtActionPerformed

    private void startTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTxtActionPerformed

    private void createEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventBtnActionPerformed
       
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/eventdatabase","root","");
            System.out.println("Connection Successful");
            this.setID();
            String cus = "CUS" + uniqueNum;
                // create a Statement from the connection
Statement statement = conn.createStatement();
Statement customer = conn.createStatement();
Statement address = conn.createStatement();
Statement items = conn.createStatement();

// insert the data
statement.executeUpdate("INSERT INTO events VALUES ('" + ID + "', '"+ cus +"','"+ roomComboBox.getSelectedItem() +"', '"+ numOfGuests.getText()+"', '"+ startDateTxt.getText()+"', '"+endDateTxt.getText()+"','"+getTotalPrice()+"')");
customer.executeUpdate("INSERT INTO customer VALUES('"+ cus +"', '"+ customerNameTxt.getText()+"','"+internal+"','"+telTxt.getText()+"','"+emailTxt.getText()+"')");
address.executeUpdate("INSERT INTO address VALUES('"+ cus +"','"+ streetNameTxt.getText()+"','"+ houseNumberTxt.getText() +"','"+ postCodeTxt.getText() +"' )");
for (Item item: itemList)
{
items.executeUpdate("INSERT INTO eventitems VALUES('"+ ID +"','"+ item.getName() +"','"+ item.getQuantity()+"')");
}
    }
        catch (Exception e)
    {
      System.err.println("D'oh! Got an exception9!"); 
      e.printStackTrace();
      System.err.println(e.getMessage()); 
    
    } 
    }//GEN-LAST:event_createEventBtnActionPerformed

    private void customerNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        streetNameTxt.setText("");
        postCodeTxt.setText("");
        customerNameTxt.setText("");
        houseNumberTxt.setText("");
        startTxt.setText("");
        endTxt.setText("");
        startDateTxt.setText("");
        selectedMenus.setText("");
        selectedDrinks.setText("");
        quantityMenuCombo.setSelectedIndex(0);
        quantityDrinksCombo.setSelectedIndex(0);
        totalPrice = 0.00;
        totalTxt.setText(totalPrice.toString());
        
    }//GEN-LAST:event_clearBtnActionPerformed
        // Creates menu Item objects
        Item menu1 = new Item("Menu 1",50.00,0);
        Item menu2 = new Item("Menu 2",120.00,0);
        Item menu3 = new Item("Menu 3",180.00,0);
        Item menu4 =new Item("Menu 4",250.00,0);
        Item champagne = new Item ("Champagne",30.00,0);
        Item beer = new Item ("Beer",3.50,0);
        Item orange = new Item ("Orange Juice",2.00,0);
        Item redWine = new Item ("Red Wine",5.50,0);
        Item whiteWine = new Item("White Wine",5.50,0);
        Item apple = new Item("Apple Juice", 2.00,0);
        
    private void menuComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComboActionPerformed
        String menu =(String)menuCombo.getSelectedItem();
        
        if(menu == menu1.getName())
        {
            int num = menu1.getQuantity();
           String quantity = (String)quantityMenuCombo.getSelectedItem();
           menu1.setQuantity(Integer.parseInt(quantity));
           selectedMenus.append(menu1.toString());
           setTotalPrice(menu1.getPrice() * menu1.getQuantity());
           itemList.add(menu1);
        }
        else if(menu == menu2.getName())
                {
                    int num = menu2.getQuantity();
                    String quantity = (String)quantityMenuCombo.getSelectedItem();
                    menu2.setQuantity(Integer.parseInt(quantity) + num);
                    selectedMenus.append(menu2.toString());
                    double price = menu2.getPrice() * menu2.getQuantity();
                    setTotalPrice(price);
                    itemList.add(menu2);
                }
        else if(menu == menu3.getName())
                {
                    int num = menu3.getQuantity();
                    String quantity = (String)quantityMenuCombo.getSelectedItem();
                    menu3.setQuantity(Integer.parseInt(quantity));
                    selectedMenus.append(menu3.toString()); 
                    setTotalPrice(menu3.getPrice() * menu3.getQuantity());
                    itemList.add(menu3);
                }
        else if(menu == menu4.getName())
                {
                    int num = menu4.getQuantity();
                    String quantity = (String)quantityMenuCombo.getSelectedItem();
                    menu4.setQuantity(Integer.parseInt(quantity));
                    selectedMenus.append(menu4.toString()); 
                    setTotalPrice(menu4.getPrice() * menu4.getQuantity());
                    itemList.add(menu4);
                }
    }//GEN-LAST:event_menuComboActionPerformed

    private void drinksComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksComboActionPerformed
        String drink =(String)drinksCombo.getSelectedItem();
        
        if(drink == champagne.getName())
        {
           String quantity = (String)quantityDrinksCombo.getSelectedItem();
           champagne.setQuantity(Integer.parseInt(quantity));
           selectedDrinks.append(champagne.toString());
           setTotalPrice(champagne.getPrice() * champagne.getQuantity());
           itemList.add(champagne);
        }
        else if(drink == beer.getName())
                {
                    String quantity = (String)quantityDrinksCombo.getSelectedItem();
                    beer.setQuantity(Integer.parseInt(quantity));
                    selectedDrinks.append(beer.toString());
                    setTotalPrice(beer.getPrice() * beer.getQuantity());
                     itemList.add(beer);
                }
        else if(drink == redWine.getName())
                {
                    String quantity = (String)quantityDrinksCombo.getSelectedItem();
                    redWine.setQuantity(Integer.parseInt(quantity));
                    selectedDrinks.append(redWine.toString());
                    setTotalPrice(redWine.getPrice() * redWine.getQuantity());
                    itemList.add(redWine);
                }
        else if(drink == whiteWine.getName())
                {
                    String quantity = (String)quantityDrinksCombo.getSelectedItem();
                    whiteWine.setQuantity(Integer.parseInt(quantity));
                    selectedDrinks.append(whiteWine.toString());
                    setTotalPrice(whiteWine.getPrice() * whiteWine.getQuantity());
                    itemList.add(whiteWine);
                }
        else if(drink == orange.getName())
                {
                    String quantity = (String)quantityDrinksCombo.getSelectedItem();
                    orange.setQuantity(Integer.parseInt(quantity));
                    selectedDrinks.append(orange.toString());
                    setTotalPrice(orange.getPrice() * orange.getQuantity());
                    itemList.add(orange);
                }
        else if(drink == apple.getName())
                {
                    String quantity = (String)quantityDrinksCombo.getSelectedItem();
                    apple.setQuantity(Integer.parseInt(quantity));
                    selectedDrinks.append(apple.toString());
                    setTotalPrice(apple.getPrice() * apple.getQuantity());
                    itemList.add(apple);
                }
    }//GEN-LAST:event_drinksComboActionPerformed

    private void interRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interRBtnActionPerformed
        internal = 1;
        exterRBtn.setSelected(false);
    }//GEN-LAST:event_interRBtnActionPerformed

    private void exterRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exterRBtnActionPerformed
        internal = 2;
        interRBtn.setSelected(false);
    }//GEN-LAST:event_exterRBtnActionPerformed

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed
    
    /**
     * Displays the event details from the database.
     */
    public void openEvent(String id)
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/eventdatabase","root","");
            System.out.println("Connection Successful");
            String customerID = "";
            Statement stmt = conn.createStatement();
            Statement customerD = conn.createStatement();
            Statement address = conn.createStatement();
            Statement items = conn.createStatement();

            ResultSet event;
            ResultSet cust;
 
            event = stmt.executeQuery("SELECT * FROM events WHERE EventID = '"+id + "'");
            
                while (event.next())
                {
                int totalPrice = (event.getInt("TotalPrice"));
                customerID = event.getString("CustomerID");
                String room = event.getString("RoomName");
                int numGuest = event.getInt("NumberGuests");
                String startDate = event.getString("StartDate");
                String endDate = event.getString("EndDate");
                String guests = Integer.toString(numGuest);
                String total = Integer.toString(totalPrice);
                totalTxt.setText(total);
                numOfGuests.setText(guests);
                startDateTxt.setText(startDate);
                endDateTxt.setText(endDate);
                }
                
                cust = customerD.executeQuery("SELECT * FROM customer WHERE CustomerID = '"+customerID + "'");
                while (cust.next())
                {
                    customerNameTxt.setText(cust.getString("Name"));
                    telTxt.setText(cust.getString("Telephone"));
                    emailTxt.setText(cust.getString("Email"));
                }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception3! ");
            System.err.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton createEventBtn;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JComboBox<String> drinksCombo;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField endDateTxt;
    private javax.swing.JTextField endTxt;
    private javax.swing.JRadioButton exterRBtn;
    private javax.swing.JTextField houseNumberTxt;
    private javax.swing.JRadioButton interRBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> menuCombo;
    private javax.swing.JTextField numOfGuests;
    private javax.swing.JTextField postCodeTxt;
    private javax.swing.JComboBox<String> quantityDrinksCombo;
    private javax.swing.JComboBox<String> quantityMenuCombo;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JTextArea selectedDrinks;
    private javax.swing.JTextArea selectedMenus;
    private javax.swing.JTextField startDateTxt;
    private javax.swing.JTextField startTxt;
    private javax.swing.JTextField streetNameTxt;
    private javax.swing.JTextField telTxt;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables
}
